#############################################################################
# Makefile for building: TicTacToe
# Generated by qmake (2.01a) (Qt 4.6.2) on: Mon Nov 22 17:52:41 2010
# Project:  TicTacToe.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -unix -o Makefile TicTacToe.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		tictactoe.cpp \
		gamesquare.cpp \
		gamegrid.cpp \
		gameengine.cpp moc_tictactoe.cpp \
		moc_gamesquare.cpp
OBJECTS       = main.o \
		tictactoe.o \
		gamesquare.o \
		gamegrid.o \
		gameengine.o \
		moc_tictactoe.o \
		moc_gamesquare.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		TicTacToe.pro
QMAKE_TARGET  = TicTacToe
DESTDIR       = 
TARGET        = TicTacToe

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TicTacToe.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile TicTacToe.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile TicTacToe.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/TicTacToe1.0.0 || $(MKDIR) .tmp/TicTacToe1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/TicTacToe1.0.0/ && $(COPY_FILE) --parents tictactoe.h gamesquare.h gamegrid.h gameengine.h .tmp/TicTacToe1.0.0/ && $(COPY_FILE) --parents main.cpp tictactoe.cpp gamesquare.cpp gamegrid.cpp gameengine.cpp .tmp/TicTacToe1.0.0/ && (cd `dirname .tmp/TicTacToe1.0.0` && $(TAR) TicTacToe1.0.0.tar TicTacToe1.0.0 && $(COMPRESS) TicTacToe1.0.0.tar) && $(MOVE) `dirname .tmp/TicTacToe1.0.0`/TicTacToe1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/TicTacToe1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_tictactoe.cpp moc_gamesquare.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_tictactoe.cpp moc_gamesquare.cpp
moc_tictactoe.cpp: gamesquare.h \
		gamegrid.h \
		gameengine.h \
		tictactoe.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) tictactoe.h -o moc_tictactoe.cpp

moc_gamesquare.cpp: gamesquare.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) gamesquare.h -o moc_gamesquare.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp tictactoe.h \
		gamesquare.h \
		gamegrid.h \
		gameengine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

tictactoe.o: tictactoe.cpp tictactoe.h \
		gamesquare.h \
		gamegrid.h \
		gameengine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tictactoe.o tictactoe.cpp

gamesquare.o: gamesquare.cpp gamesquare.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gamesquare.o gamesquare.cpp

gamegrid.o: gamegrid.cpp gamegrid.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gamegrid.o gamegrid.cpp

gameengine.o: gameengine.cpp gameengine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gameengine.o gameengine.cpp

moc_tictactoe.o: moc_tictactoe.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tictactoe.o moc_tictactoe.cpp

moc_gamesquare.o: moc_gamesquare.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gamesquare.o moc_gamesquare.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

